"""Programmatic generators for `.github/workflows/security.yml` and
`.github/dependabot.yml`.

Three workflow templates:
  - MINIMAL:  dependency-review + python-sast (ruff-sec + pip-audit) + zizmor
  - STANDARD: MINIMAL + CodeQL default suite + harden-runner audit mode
  - PARANOID: STANDARD + Scorecard (weekly) + CodeQL security-extended on schedule

All action `uses:` lines are rendered via `PinnedAction.render()` so every
reference carries a 40-char SHA and a `# vX.Y.Z` comment. Dependabot keeps
those current.
"""

from __future__ import annotations

from enum import Enum

from duh.security.ci_templates import PINNED_ACTIONS, PinnedAction

__all__ = ["WorkflowTemplate", "generate_workflow", "generate_dependabot"]


class WorkflowTemplate(str, Enum):
    MINIMAL = "minimal"
    STANDARD = "standard"
    PARANOID = "paranoid"


def _pin(name: str) -> str:
    return PINNED_ACTIONS[name].render()


_HEADER = """\
# Generated by `duh security generate workflow`.
# ADR-053: continuous vulnerability monitoring.
#
# Do not edit by hand. Re-run the generator to update.
# All GitHub Actions pinned to 40-char SHAs; Dependabot keeps them fresh.
name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '17 4 * * 1'  # weekly, Mondays 04:17 UTC

permissions:
  contents: read

"""


_HARDEN_RUNNER_STEP = f"""\
      - name: Harden runner
        uses: {_pin("step-security/harden-runner")}
        with:
          egress-policy: audit
"""


def _with_harden_runner(job_body: str) -> str:
    # Insert harden-runner as the first step immediately after `steps:`.
    return job_body.replace(
        "    steps:\n      - uses: " + _pin("actions/checkout"),
        "    steps:\n" + _HARDEN_RUNNER_STEP + "      - uses: " + _pin("actions/checkout"),
    )


def _dependency_review_job() -> str:
    return f"""\
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: {_pin("actions/checkout")}
      - name: Dependency review
        uses: {_pin("actions/dependency-review-action")}
        with:
          fail-on-severity: high
          comment-summary-in-pr: on-failure

"""


def _python_sast_job() -> str:
    return f"""\
  python-sast:
    name: Python SAST (ruff-sec + pip-audit)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: {_pin("actions/checkout")}
      - name: Set up Python
        uses: {_pin("actions/setup-python")}
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Cache pip
        uses: {_pin("actions/cache")}
        with:
          path: ~/.cache/pip
          key: ${{{{ runner.os }}}}-pip-${{{{ hashFiles('pyproject.toml') }}}}
          restore-keys: |
            ${{{{ runner.os }}}}-pip-
      - name: Install D.U.H. security extras
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[security]"
      - name: Run duh security scan (SARIF)
        run: duh security scan --sarif-out security.sarif --fail-on=high
      - name: Upload SARIF
        if: always()
        uses: {_pin("actions/upload-artifact")}
        with:
          name: duh-security-sarif
          path: security.sarif
          if-no-files-found: warn
      - name: Upload SARIF to code scanning
        if: always()
        uses: {_pin("github/codeql-action/upload-sarif")}
        with:
          sarif_file: security.sarif
          category: duh-security

"""


def _workflow_audit_job() -> str:
    return f"""\
  workflow-audit:
    name: Workflow audit (zizmor)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: {_pin("actions/checkout")}
      - name: Run zizmor
        uses: {_pin("zizmorcore/zizmor-action")}
        with:
          advisories: all

"""


def _codeql_job() -> str:
    return f"""\
  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Harden runner
        uses: {_pin("step-security/harden-runner")}
        with:
          egress-policy: audit
      - uses: {_pin("actions/checkout")}
      - name: Initialize CodeQL
        uses: {_pin("github/codeql-action/init")}
        with:
          languages: python
          build-mode: none
          queries: ${{{{ github.event_name == 'schedule' && 'security-extended' || 'security-and-quality' }}}}
      - name: Perform CodeQL analysis
        uses: {_pin("github/codeql-action/analyze")}
        with:
          category: "/language:python"

"""


def _scorecard_job() -> str:
    return f"""\
  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Harden runner
        uses: {_pin("step-security/harden-runner")}
        with:
          egress-policy: audit
      - uses: {_pin("actions/checkout")}
        with:
          persist-credentials: false
      - name: Run Scorecard
        uses: {_pin("ossf/scorecard-action")}
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard SARIF
        if: always()
        uses: {_pin("actions/upload-artifact")}
        with:
          name: scorecard-sarif
          path: scorecard.sarif
          if-no-files-found: warn
      - name: Upload Scorecard to code scanning
        if: always()
        uses: {_pin("github/codeql-action/upload-sarif")}
        with:
          sarif_file: scorecard.sarif
          category: scorecard

"""


def generate_workflow(template: WorkflowTemplate) -> str:
    """Return a rendered `.github/workflows/security.yml` body."""
    if template == WorkflowTemplate.MINIMAL:
        jobs = (
            "jobs:\n"
            + _dependency_review_job()
            + _python_sast_job()
            + _workflow_audit_job()
        )
        return _HEADER + jobs
    if template == WorkflowTemplate.STANDARD:
        jobs = (
            "jobs:\n"
            + _with_harden_runner(_dependency_review_job())
            + _with_harden_runner(_python_sast_job())
            + _with_harden_runner(_workflow_audit_job())
            + _codeql_job()
        )
        return _HEADER + jobs
    if template == WorkflowTemplate.PARANOID:
        jobs = (
            "jobs:\n"
            + _with_harden_runner(_dependency_review_job())
            + _with_harden_runner(_python_sast_job())
            + _with_harden_runner(_workflow_audit_job())
            + _codeql_job()
            + _scorecard_job()
        )
        return _HEADER + jobs
    raise NotImplementedError(f"template not yet implemented: {template}")


_DEPENDABOT_BODY = """\
# Generated by `duh security generate dependabot`.
# ADR-053: continuous vulnerability monitoring.
#
# Weekly grouped updates for pip + github-actions ecosystems.
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      python-deps:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
"""


def generate_dependabot() -> str:
    """Return a rendered `.github/dependabot.yml` body."""
    return _DEPENDABOT_BODY
